// Sidebar tree + search index data

const SIDEBAR = [
  {
    items: [
      { id: "intro", label: "Introduction", page: "intro" },
      { id: "install", label: "Install s&box", page: "install" },
      { id: "first-game", label: "Your first game", page: "first-game" },
      { id: "editor-tour", label: "Editor tour", page: "editor-tour" },
    ],
    title: "Getting Started",
  },
  {
    items: [
      {
        current: true,
        id: "tut-component",
        label: "Writing a Component",
        page: "tut-component",
      },
      { id: "tut-input", label: "Player input & movement", page: "tut-input" },
      { id: "tut-network", label: "Networking basics", page: "tut-network" },
      { id: "tut-shader", label: "Custom shaders", page: "tut-shader" },
      { id: "tut-ui", label: "Building UI with Razor", page: "tut-ui" },
    ],
    title: "Tutorials",
  },
  {
    items: [
      { id: "mcp-setup", label: "Setup MCP server", page: "mcp-setup" },
      { id: "mcp-vscode", label: "Add to VS Code", page: "mcp-vscode" },
      { id: "mcp-cursor", label: "Add to Cursor", page: "mcp-cursor" },
      { id: "mcp-claude", label: "Add to Claude Desktop", page: "mcp-claude" },
    ],
    title: "MCP integration",
  },
  {
    items: [
      {
        children: [
          {
            id: "cls-gameobject",
            kind: "C",
            label: "GameObject",
            page: "gameobject",
          },
          {
            children: [
              {
                anchor: "prop-GameObject",
                id: "p-gameobject",
                kind: "P",
                label: "GameObject",
              },
              {
                anchor: "prop-Transform",
                id: "p-transform",
                kind: "P",
                label: "Transform",
              },
              { anchor: "prop-Tags", id: "p-tags", kind: "P", label: "Tags" },
              {
                anchor: "prop-Enabled",
                id: "p-enabled",
                kind: "P",
                label: "Enabled",
              },
              {
                anchor: "prop-Active",
                id: "p-active",
                kind: "P",
                label: "Active",
              },
              {
                anchor: "prop-Network",
                id: "p-network",
                kind: "P",
                label: "Network",
              },
              {
                anchor: "prop-Scene",
                id: "p-scene",
                kind: "P",
                label: "Scene",
              },
              {
                anchor: "method-OnAwake",
                id: "m-onawake",
                kind: "M",
                label: "OnAwake()",
              },
              {
                anchor: "method-OnStart",
                id: "m-onstart",
                kind: "M",
                label: "OnStart()",
              },
              {
                anchor: "method-OnUpdate",
                id: "m-onupdate",
                kind: "M",
                label: "OnUpdate()",
              },
              {
                anchor: "method-OnDestroy",
                id: "m-ondestroy",
                kind: "M",
                label: "OnDestroy()",
              },
              {
                anchor: "method-GetComponent",
                id: "m-getcomp",
                kind: "M",
                label: "GetComponent<T>",
              },
              {
                anchor: "method-Destroy",
                id: "m-destroy",
                kind: "M",
                label: "Destroy()",
              },
            ],
            current: true,
            expanded: true,
            id: "cls-component",
            kind: "C",
            label: "Component",
            page: "component",
          },
          { id: "cls-scene", kind: "C", label: "Scene", page: "scene" },
          {
            id: "cls-transform",
            kind: "C",
            label: "GameTransform",
            page: "gametransform",
          },
          { id: "cls-tagset", kind: "C", label: "TagSet", page: "tagset" },
          { id: "cls-input", kind: "S", label: "Input", page: "input" },
          { id: "cls-time", kind: "S", label: "Time", page: "time" },
        ],
        expanded: true,
        id: "ns-sandbox",
        label: "Sandbox",
      },
      {
        children: [
          { id: "cls-rigid", kind: "C", label: "Rigidbody", page: "rigidbody" },
          {
            id: "cls-collider",
            kind: "C",
            label: "Collider",
            page: "collider",
          },
          {
            id: "cls-trace",
            kind: "C",
            label: "SceneTrace",
            page: "scenetrace",
          },
        ],
        id: "ns-physics",
        label: "Sandbox.Physics",
      },
      {
        children: [
          {
            id: "cls-conn",
            kind: "C",
            label: "Connection",
            page: "connection",
          },
          { id: "cls-rpc", kind: "A", label: "Rpc", page: "rpc" },
          { id: "cls-sync", kind: "A", label: "Sync", page: "sync" },
        ],
        id: "ns-network",
        label: "Sandbox.Network",
      },
      {
        children: [
          { id: "cls-panel", kind: "C", label: "Panel", page: "panel" },
          {
            id: "cls-screen",
            kind: "C",
            label: "ScreenPanel",
            page: "screenpanel",
          },
        ],
        id: "ns-ui",
        label: "Sandbox.UI",
      },
    ],
    title: "API Reference",
  },
];

// Search index — flat list of everything searchable
const SEARCH_INDEX = [
  // API ref
  {
    desc: "Base class for behaviour attached to GameObjects.",
    name: "Component",
    page: "component",
    path: "Sandbox.Component",
    type: "class",
  },
  {
    desc: "An entity in a scene that holds components and transforms.",
    name: "GameObject",
    page: "gameobject",
    path: "Sandbox.GameObject",
    type: "class",
  },
  {
    desc: "Container for GameObjects and the simulation root.",
    name: "Scene",
    page: "scene",
    path: "Sandbox.Scene",
    type: "class",
  },
  {
    desc: "Position, rotation, scale of a GameObject.",
    name: "GameTransform",
    page: "gametransform",
    path: "Sandbox.GameTransform",
    type: "class",
  },
  {
    desc: "Adds physics simulation to a GameObject.",
    name: "Rigidbody",
    page: "rigidbody",
    path: "Sandbox.Physics.Rigidbody",
    type: "class",
  },
  {
    desc: "Defines a collision shape.",
    name: "Collider",
    page: "collider",
    path: "Sandbox.Physics.Collider",
    type: "class",
  },
  {
    desc: "Raycast and shape-cast against the scene.",
    name: "SceneTrace",
    page: "scenetrace",
    path: "Sandbox.Physics.SceneTrace",
    type: "class",
  },
  {
    desc: "A connected network peer.",
    name: "Connection",
    page: "connection",
    path: "Sandbox.Network.Connection",
    type: "class",
  },
  {
    desc: "Base class for Razor UI panels.",
    name: "Panel",
    page: "panel",
    path: "Sandbox.UI.Panel",
    type: "class",
  },
  {
    desc: "Root panel rendered to the screen.",
    name: "ScreenPanel",
    page: "screenpanel",
    path: "Sandbox.UI.ScreenPanel",
    type: "class",
  },
  {
    desc: "Static input access — buttons, axes, mouse.",
    name: "Input",
    page: "input",
    path: "Sandbox.Input",
    type: "static",
  },
  {
    desc: "Frame and fixed-step time accessors.",
    name: "Time",
    page: "time",
    path: "Sandbox.Time",
    type: "static",
  },
  {
    desc: "Mark a method as a remote procedure call.",
    name: "Rpc",
    page: "rpc",
    path: "Sandbox.Network.Rpc",
    type: "attr",
  },
  {
    desc: "Mark a property as network-synced.",
    name: "Sync",
    page: "sync",
    path: "Sandbox.Network.Sync",
    type: "attr",
  },

  // Members of Component
  {
    anchor: "prop-GameObject",
    desc: "The GameObject this component is attached to.",
    name: "GameObject",
    page: "component",
    path: "Component.GameObject",
    type: "prop",
  },
  {
    anchor: "prop-Transform",
    desc: "Shortcut to GameObject.Transform.",
    name: "Transform",
    page: "component",
    path: "Component.Transform",
    type: "prop",
  },
  {
    anchor: "prop-Enabled",
    desc: "Whether this component is enabled.",
    name: "Enabled",
    page: "component",
    path: "Component.Enabled",
    type: "prop",
  },
  {
    anchor: "prop-Active",
    desc: "Enabled AND its GameObject is active.",
    name: "Active",
    page: "component",
    path: "Component.Active",
    type: "prop",
  },
  {
    anchor: "method-OnAwake",
    desc: "Called once when the component is created.",
    name: "OnAwake()",
    page: "component",
    path: "Component.OnAwake",
    type: "method",
  },
  {
    anchor: "method-OnStart",
    desc: "Called once before the first update.",
    name: "OnStart()",
    page: "component",
    path: "Component.OnStart",
    type: "method",
  },
  {
    anchor: "method-OnUpdate",
    desc: "Called every frame.",
    name: "OnUpdate()",
    page: "component",
    path: "Component.OnUpdate",
    type: "method",
  },
  {
    anchor: "method-OnDestroy",
    desc: "Called before destruction.",
    name: "OnDestroy()",
    page: "component",
    path: "Component.OnDestroy",
    type: "method",
  },
  {
    anchor: "method-GetComponent",
    desc: "Find a sibling component by type.",
    name: "GetComponent<T>()",
    page: "component",
    path: "Component.GetComponent",
    type: "method",
  },
  {
    anchor: "method-Destroy",
    desc: "Remove this component from its GameObject.",
    name: "Destroy()",
    page: "component",
    path: "Component.Destroy",
    type: "method",
  },

  // Tutorials
  {
    desc: "Build your first behaviour script in s&box.",
    name: "Writing a Component",
    page: "tut-component",
    path: "Tutorials / Component",
    type: "guide",
  },
  {
    desc: "Wire keyboard and mouse to a controllable character.",
    name: "Player input & movement",
    page: "tut-input",
    path: "Tutorials / Input",
    type: "guide",
  },
  {
    desc: "Sync state and call methods across the network.",
    name: "Networking basics",
    page: "tut-network",
    path: "Tutorials / Networking",
    type: "guide",
  },
  {
    desc: "Author HLSL shaders for s&box materials.",
    name: "Custom shaders",
    page: "tut-shader",
    path: "Tutorials / Shaders",
    type: "guide",
  },
  {
    desc: "Compose UIs with .razor templates.",
    name: "Building UI with Razor",
    page: "tut-ui",
    path: "Tutorials / UI",
    type: "guide",
  },

  // MCP
  {
    desc: "Run the docs MCP locally or remotely.",
    name: "Setup MCP server",
    page: "mcp-setup",
    path: "MCP / Setup",
    type: "guide",
  },
  {
    desc: "Install the s&box docs MCP in VS Code.",
    name: "Add to VS Code",
    page: "mcp-vscode",
    path: "MCP / VS Code",
    type: "guide",
  },
  {
    desc: "Install the s&box docs MCP in Cursor.",
    name: "Add to Cursor",
    page: "mcp-cursor",
    path: "MCP / Cursor",
    type: "guide",
  },
  {
    desc: "Install the s&box docs MCP in Claude Desktop.",
    name: "Add to Claude Desktop",
    page: "mcp-claude",
    path: "MCP / Claude",
    type: "guide",
  },
];

window.SIDEBAR = SIDEBAR;
window.SEARCH_INDEX = SEARCH_INDEX;
